name: Instagram Automation

on:
  schedule:
    # Runs every day at 10:00 AM IST (which is 04:30 UTC)
    - cron: "30 4 * * *"
  workflow_dispatch: # allows manual run

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create Google credentials file
        run: |
          echo "${{ secrets.GOOGLE_CREDENTIALS_JSON }}" > service_account.json

      - name: Run automation script
        env:
          GOOGLE_CREDENTIALS_PATH: service_account.json
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
          SHEET_NAME: ${{ secrets.SHEET_NAME }}
          INSTAGRAM_ACCOUNT_ID: ${{ secrets.INSTAGRAM_ACCOUNT_ID }}
          INSTAGRAM_ACCESS_TOKEN: ${{ secrets.INSTAGRAM_ACCESS_TOKEN }}
        run: |
          python insta_automation_langgraph.py
